name: Deploy Flask App to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: 18.191.205.102

      - name: Copy project to EC2 (SCP)
        run: |
          scp -i ~/.ssh/id_rsa -r ./ $EC2_USER@$EC2_HOST:/home/$EC2_USER/groupe2
        env:
          EC2_USER: ubuntu
          EC2_HOST: 18.191.205.102

      - name: Install dependencies and run app
        run: |
          ssh $EC2_USER@$EC2_HOST << EOF
          cd /home/$EC2_USER/groupe2
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt
          nohup venv/bin/python app.py > app.log 2>&1 &
          EOF
        env:
          EC2_USER: ubuntu
          EC2_HOST: 18.191.205.102
